# Host-side installation of the devbox router.
# Source this file; do not execute it. It needs bootstrap/lib/common.sh.
#
# The router is the one host component every other host component routes
# through, so it installs on its own and installs nothing else. It creates no
# container and it writes no credential.
#
# It needs bootstrap/lib/environments.sh: the environment files and the
# inference rules come from the environment modules, never from a list here.

# install_devbox_router <repo-root> [home]
#
# Installs the router, its verification suite, the compatibility wrappers, the
# agent host shims and the router configuration.
install_devbox_router() {
    local repo_root=$1
    local home=${2:-$HOME}
    local cfg=$home/.config/devbox-router
    local tool

    section 'Directories'
    ensure_dir_reported "$home/projects"
    ensure_dir_reported "$home/.local/bin"
    ensure_dir_reported "$cfg/environments.d"

    section 'devbox router (~/.local/bin)'
    for tool in devbox devbox-verify devbox-run web-dev-run; do
        link_into "$repo_root/bin/$tool" "$home/.local/bin/$tool"
    done

    section 'Agent host shims'
    # The shims are generated by the router itself, so their content never
    # drifts from the router that consumes them. 'devbox new-shim' refuses to
    # overwrite. claude and codex are created only when the path is absent, so
    # a hand edit survives.
    for tool in claude codex; do
        if [ -e "$home/.local/bin/$tool" ]; then
            ok "$home/.local/bin/$tool"
        else
            run env DEVBOX_SHIM_DIR="$home/.local/bin" "$repo_root/bin/devbox" new-shim "$tool" \
                && change "$home/.local/bin/$tool"
        fi
    done
    install_grok_host_shim "$repo_root" "$home"
    retire_host_grok_installer_path "$home"

    section 'devbox router configuration (~/.config/devbox-router)'
    link_into "$repo_root/config/devbox-router/README.md"    "$cfg/README.md"
    link_into "$repo_root/config/devbox-router/settings.env" "$cfg/settings.env"
    install_router_environments "$repo_root" "$cfg"
    install_inference_rules "$repo_root" "$cfg/inference.tsv"
    # repos.tsv holds absolute host paths. It is machine state: seed it once,
    # then leave it to 'devbox assign'.
    install_if_absent "$repo_root/config/devbox-router/repos.tsv.template" "$cfg/repos.tsv"
}

# install_grok_host_shim <repo-root> <home>
#
# Writes the resolved grok shim. A file that already carries the shim header
# is left alone, including a later hand edit. Any other file at that path is
# the upstream installer link. The host command has to be the shim, so that
# file is replaced. The copy goes to the backup directory first.
install_grok_host_shim() {
    local repo_root=$1 home=$2
    local dest=$home/.local/bin/grok tmp alias target

    if [ -f "$dest" ] && [ ! -L "$dest" ] && grep -q "Host shim for 'grok'" "$dest" 2>/dev/null; then
        ok "$dest"
    else
        if [ -e "$dest" ] || [ -L "$dest" ]; then
            save_copy "$dest"
            warn "$dest is not the devbox shim; a copy is in $(backup_dir)"
            run rm -f -- "$dest"
        fi
        if [ "$DRY_RUN" = 1 ]; then
            info "would write the grok host shim to $dest"
        else
            tmp=$(mktemp) || die 'cannot create a temporary file'
            "$repo_root/bin/devbox" new-shim grok --print > "$tmp" \
                || die 'the devbox router could not generate the grok host shim'
            install_file "$tmp" "$dest" 0755
            rm -f -- "$tmp"
        fi
    fi

    # The upstream installer also links the name "agent" at this directory.
    # That name is not a router shim. Remove it only when it points at Grok.
    alias=$home/.local/bin/agent
    if [ -L "$alias" ]; then
        target=$(readlink -f -- "$alias" 2>/dev/null || true)
        case $target in
            */.grok/bin/grok|*/.grok/bin/agent|*/.grok/downloads/grok-*)
                save_copy "$alias"
                run rm -f -- "$alias" && change "removed the host Grok alias $alias"
                ;;
        esac
    fi
}

# retire_host_grok_installer_path <home>
#
# The upstream installer prepends ~/.grok/bin to the host shell PATH.
# That directory wins over the shim, so the host command never enters an
# environment. Remove the marked block. The binary under ~/.grok/bin stays.
# A development environment keeps its own block: there the directory is the
# real Grok binary, inside the isolated HOME.
retire_host_grok_installer_path() {
    local home=$1 file tmp
    if [ -f /run/.containerenv ] || [ -f /.dockerenv ]; then
        return 0
    fi
    for file in "$home/.bashrc" "$home/.zshrc" "$home/.config/fish/config.fish"; do
        [ -f "$file" ] || continue
        grep -q '>>> grok installer >>>' "$file" || continue
        save_copy "$file"
        tmp=$(mktemp) || die 'cannot create a temporary file'
        awk '
            /# >>> grok installer >>>/ { skip=1; next }
            /# <<< grok installer <<</ { skip=0; next }
            !skip { print }
        ' "$file" > "$tmp"
        run cp -- "$tmp" "$file" && change "removed the host Grok PATH block from $file"
        rm -f -- "$tmp"
    done
}

# install_router_environments <repo-root> <config-dir>
#
# Links the router file of every supported environment module. The module
# names the file it owns, so an environment is added by adding a module.
install_router_environments() {
    local repo_root=$1 cfg=$2
    local id status container ini packages toolchain bootstrap router inference home

    if ! have python3; then
        warn 'python3 is not installed; the environment modules cannot be read'
        manual 'Install python3 on the host, then re-run the installer'
        return 0
    fi
    while IFS=$'\t' read -r id status container ini packages toolchain \
        bootstrap router inference home; do
        [ -n "$router" ] && [ "$router" != - ] || continue
        link_into "$repo_root/$router" "$cfg/environments.d/$id.env"
    done < <(environment_modules "$repo_root" supported)
}

# install_inference_rules <repo-root> <dest>
#
# Assembles the inference table from the environment modules. It is generated
# rather than linked, because it is the one file the router reads that several
# modules own together.
install_inference_rules() {
    local repo_root=$1 dest=$2 tmp

    tmp=$(mktemp) || die 'cannot create a temporary file'
    {
        printf '# Automatic environment inference:\n'
        printf '#     <environment><TAB><file or glob at repo root>[<TAB>specific]\n'
        printf '#\n'
        printf '# GENERATED from components/*/inference.tsv. Edit the module, not this file.\n'
        printf '#\n'
        printf '# Only used when a repository has no explicit declaration or assignment.\n'
        printf '# If patterns for MORE THAN ONE environment match, routing fails on purpose\n'
        printf '# rather than picking arbitrarily. Patterns must not contain whitespace.\n'
        printf '#\n'
        printf '# The third field is the tier, "general" when it is absent. Resolution keeps\n'
        printf '# the strongest tier that matched, so a "specific" marker outranks the\n'
        printf '# general markers of another environment. Ambiguity inside the winning\n'
        printf '# tier still fails.\n'
        environment_rules "$repo_root"
    } > "$tmp"

    # An earlier release linked this path into the checkout. Remove the link so
    # that the generated file replaces it. The link holds nothing of its own,
    # and install_file backs up whatever it overwrites.
    if [ -L "$dest" ]; then
        run rm -f -- "$dest"
    fi

    install_file "$tmp" "$dest"
    rm -f -- "$tmp"
}
