# Host-side installation of the devbox router.
# Source this file; do not execute it. It needs bootstrap/lib/common.sh.
#
# The router is the one host component every other host component routes
# through, so it installs on its own and installs nothing else. It creates no
# container and it writes no credential.

# install_devbox_router <repo-root> [home]
#
# Installs the router, its verification suite, the compatibility wrappers, the
# agent host shims and the router configuration.
install_devbox_router() {
    local repo_root=$1
    local home=${2:-$HOME}
    local cfg=$home/.config/devbox-router
    local tool

    section 'Directories'
    ensure_dir_reported "$home/projects"
    ensure_dir_reported "$home/.local/bin"
    ensure_dir_reported "$cfg/environments.d"

    section 'devbox router (~/.local/bin)'
    for tool in devbox devbox-verify devbox-run web-dev-run; do
        link_into "$repo_root/bin/$tool" "$home/.local/bin/$tool"
    done

    section 'Agent host shims'
    # The shims are generated by the router itself, so their content never
    # drifts from the router that consumes them. 'devbox new-shim' refuses to
    # overwrite.
    for tool in claude codex; do
        if [ -e "$home/.local/bin/$tool" ]; then
            ok "$home/.local/bin/$tool"
        else
            run "$repo_root/bin/devbox" new-shim "$tool" && change "$home/.local/bin/$tool"
        fi
    done

    section 'devbox router configuration (~/.config/devbox-router)'
    link_into "$repo_root/config/devbox-router/README.md"                     "$cfg/README.md"
    link_into "$repo_root/config/devbox-router/settings.env"                  "$cfg/settings.env"
    link_into "$repo_root/config/devbox-router/inference.tsv"                 "$cfg/inference.tsv"
    link_into "$repo_root/config/devbox-router/environments.d/web-dev.env"    "$cfg/environments.d/web-dev.env"
    link_into "$repo_root/config/devbox-router/environments.d/python-dev.env" "$cfg/environments.d/python-dev.env"
    # repos.tsv holds absolute host paths. It is machine state: seed it once,
    # then leave it to 'devbox assign'.
    install_if_absent "$repo_root/config/devbox-router/repos.tsv.template" "$cfg/repos.tsv"
}
